name = "dify-proxy-worker"
main = "worker.js"
compatibility_date = "2024-04-16"

account_id = "46c416f90004e48e24cba6c9ff9612ff"
workers_dev = true

[vars]
DIFY_API_KEY = "app-hlgPlVFq8vsGw2A0DPUOyIHJ"

[observability.logs]
enabled = true
