name = "sce-data-api"
main = "worker.js"
compatibility_date = "2024-04-09"
type = "javascript module"

account_id = "46c416f90004e48e24cba6c9ff9612ff"

[vars]
# zone_id = "46c416f90004e48e24cba6c9ff9612ff"

[[d1_databases]]
binding = "sce_db"
database_id = "25afcecc-cab1-404c-a19c-8686c5a664a1"